server {
    listen 8000;
    server_name _;

    # Serve static files (React build)
    location / {
        root /app/staticfiles;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API to Gunicorn
    location /api/ {
        proxy_pass http://127.0.0.1:8001; # Gunicorn on port 8001
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}