# Generated by Django 6.0.6 on 2026-06-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube'), ('google_drive', 'Google Drive'), ('facebook', 'Facebook'), ('vimeo', 'Vimeo'), ('tiktok', 'TikTok'), ('other', 'Other')], max_length=50)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('document', 'Document'), ('documentary', 'Documentary'), ('map', 'Map'), ('studycase', 'Study Case'), ('other', 'Other')], default='other', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.URLField(max_length=1024)),
                ('embed_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('downloads_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
