# Generated by Django 6.0.6 on 2026-06-04 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_external_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalmediadownload',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='media_external_manager.externalmedia'),
        ),
        migrations.AddField(
            model_name='externalmediadownload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='externalmedia',
            index=models.Index(fields=['user', '-created_at'], name='media_exter_user_id_86283d_idx'),
        ),
        migrations.AddIndex(
            model_name='externalmedia',
            index=models.Index(fields=['source_type', 'status'], name='media_exter_source__0f69c6_idx'),
        ),
        migrations.AddIndex(
            model_name='externalmedia',
            index=models.Index(fields=['media_type', 'status'], name='media_exter_media_t_ce7f6c_idx'),
        ),
    ]
