version: '3.8'

services:
  db:
    image: postgres:15
    container_name: federalism-db
    environment:
      POSTGRES_DB: ${DB_NAME:-federalism_db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-securepassword}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./src_api
    container_name: django-backend
    volumes:
      - ./src_api:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME:-federalism_db}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-securepassword}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./fed-frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: