# Generated by Django 6.0.6 on 2026-06-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image'), ('infographic', 'Infographic'), ('chart', 'Chart'), ('map', 'Map'), ('documentary', 'Documentary')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('media_file', models.FileField(blank=True, upload_to='content_media/')),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='section.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
