# Generated by Django 6.0.6 on 2026-06-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('section_type', models.CharField(choices=[('what_is', 'What is Federalism?'), ('benefits', 'Benefits'), ('drawbacks', 'Drawbacks'), ('comparisons', 'Comparisons'), ('case_studies', 'Case Studies'), ('quiz', 'Quiz/Assessment')], max_length=20)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
