# Generated by Django 6.0.6 on 2026-06-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('unitary', 'Unitary System'), ('confederal', 'Confederal System'), ('centralized', 'Centralized System')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('advantages', models.JSONField(default=list)),
                ('disadvantages', models.JSONField(default=list)),
                ('examples', models.JSONField(default=list)),
            ],
        ),
    ]
