"""
Django settings for fed_api project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from decouple import config
import os
from pathlib import Path
from urllib.parse import urlparse

from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

def parse_database_url(url):
    parsed = urlparse(url)
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parsed.path.lstrip('/') or os.environ.get('DB_NAME', 'federalism_db'),
        'USER': parsed.username or os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': parsed.password or os.environ.get('DB_PASSWORD', 'password'),
        'HOST': parsed.hostname or os.environ.get('DB_HOST', 'db'),
        'PORT': parsed.port or os.environ.get('DB_PORT', '5432'),
    }


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =os.environ.get('SECRET_KEY', 'fallback-key')
#SECRET_KEY = os.environ.get('MY_KEY', 'fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.environ.get('DEBUG','False')== 'True'

#ALLOWED_HOSTS = ['localhost','127.0.0.1']
raw_allowed = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1, http://localhost:5173, http://localhost:3000, http://localhost:8080')
ALLOWED_HOSTS = [h.strip() for h in raw_allowed.split(',') if h.strip() ]



# Application definition

INSTALLED_APPS = [
    #django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #myapps
    'users',
    'content',
    'media_manager',
    'media_external_manager',
    'section',
    'quiz',
    'question',
    'comparison',
    'caseStudy',
    'benefits',
    'drawbacks',
    'UserQuizResponse',
    
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    
    'allauth.account',
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# ---- IMPORTANT: Custom User Model ----
AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'fed_api.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fed_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
DB_HOST_ENV = os.environ.get('DB_HOST', '')

if DATABASE_URL and DATABASE_URL.startswith(('postgres://', 'postgresql://')):
    DATABASES = {'default': parse_database_url(DATABASE_URL)}
elif DB_HOST_ENV.startswith(('postgres://', 'postgresql://')):
    DATABASES = {'default': parse_database_url(DB_HOST_ENV)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', default='federalism_db'),
            'USER': os.environ.get('DB_USER', default='postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', default='password'),
            'HOST': os.environ.get('DB_HOST', default='db'),
            'PORT': os.environ.get('DB_PORT', default='5432'),
        }
    }




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================================
# FILE UPLOAD SETTINGS
# ============================================================================

# Maximum file upload size (500MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500MB

# Allowed file extensions
FILE_UPLOAD_PERMISSIONS = 0o644

# Temporary file location
FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'tmp')



# ============================================================================
# EXTERNAL MEDIA MANAGER SETTINGS
# ============================================================================

# Supported external sources
EXTERNAL_MEDIA_SOURCES = {
    'youtube': {
        'name': 'YouTube',
        'enabled': True,
        'timeout': 10,
    },
    'vimeo': {
        'name': 'Vimeo',
        'enabled': True,
        'timeout': 10,
    },
    'google_drive': {
        'name': 'Google Drive',
        'enabled': True,
        'timeout': 10,
    },
    'facebook': {
        'name': 'Facebook',
        'enabled': True,
        'timeout': 10,
    },
    'direct': {
        'name': 'Direct URL',
        'enabled': True,
        'timeout': 10,
    },
}

# Thumbnail settings
EXTERNAL_MEDIA_THUMBNAIL_SIZE = (300, 300)
EXTERNAL_MEDIA_THUMBNAIL_QUALITY = 85
EXTERNAL_MEDIA_THUMBNAIL_FORMAT = 'JPEG'

# Timeout for external requests
EXTERNAL_MEDIA_REQUEST_TIMEOUT = 10

# Maximum retries for failed requests
EXTERNAL_MEDIA_MAX_RETRIES = 3

# Cache settings for external media metadata
EXTERNAL_MEDIA_CACHE_TIMEOUT = 3600  # 1 hour

# ============================================================================
# CACHING CONFIGURATION
# ============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'media_external',
        'TIMEOUT': 3600,
    }
}

# Fallback to local memory cache if Redis is not available
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#     }
# }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        #'django_filter.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

from datetime import timedelta
SIMPLE_JWT = {
    
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    #'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    #'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),

}
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}"""



# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:8080",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    # Add your production domain
    # 'https://yourdomain.com',
]
# Allow specific headers for video streaming
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'range',  # Important for video seeking
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True






#CORS_ALLOWED_ORIGINS = config(
    #'CORS_ALLOWED_ORIGINS',
    #default='http://localhost:5173,http://localhost:3000'
#).split(',')


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

CORS_ALLOW_CREDENTIALS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend_dist'),
]

SPECTACULAR_SETTINGS = {
    'TITLE': 'src_api API',
    'DESCRIPTION': 'API for the Federalism Education Platform',
    'VERSION': '1.0.0',
}
