# Generated by Django 6.0.6 on 2026-06-04 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadownload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='media_manager.mediacategory'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediadownload',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='media_manager.mediafile'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='media_files', to='media_manager.mediatag'),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['user', '-created_at'], name='media_manag_user_id_b58565_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['media_type', 'status'], name='media_manag_media_t_18ab1a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['is_featured', '-created_at'], name='media_manag_is_feat_7f03e9_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaupload',
            index=models.Index(fields=['user', '-uploaded_at'], name='media_manag_user_id_43f0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaupload',
            index=models.Index(fields=['media_type', 'is_public'], name='media_manag_media_t_3e149d_idx'),
        ),
    ]
